### ISSUE TITLE
Expressions - Built in expressions -- error in age calculation

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#111]
I opened one of our existing Prawn xml files and a accompanying task.  When I inspect the task, there are 2 204corr206Pb/238U age equations under "Built in expressions".  One expression (highlighted in yellow in the screen snap attached) is empty (returns 0 in the viewer).  The other (which is selected in the screen snap) does return an equation but the result in wrong. The problem is that the denominator should not simply be lambda238 but lambda238*10^6 in order to return the age in Ma.
![error in age calculation](https://user-images.githubusercontent.com/40035242/41176456-f63d62b0-6b4f-11e8-8451-dd80b14e9ef0.JPG)

I haven't tried this experiment with one of your test files.  Perhaps the issue is the parsing of my SQUID2.5 task but wanted to flag.

**Comment by bowring** [comment]
1) 204corr206Pb/238U age is intentionally set to zero for now since we have not finished the internal math

2) all task equations on import are converted to be in terms of annum as that is the units of the underlying data; then, when custom reports are generated (future project), the user can specify units for display;  this is part of an architectural  model known as model-view-controller wherein there is a separation of concerns - the data does not know how it is to be viewed.  In short, Squid3 is computing values right now and will support customized views (reports) in the near future.  Squid2.50 and Isoplot mix together data and views, which makes for difficult math.  Hope this helps to convince you.

**Comment by NicoleRayner** [comment]
OK, yep this makes sense.  I figured that one of these expressions was "yours" and the math was possibly not finished and that one was "mine" from the task but I wasn't sure which was which.  I still have a question about the output though, if it is in annum why is the quotient 5.79XXXXXXX not 579XXXXXX (for6266-2.1, the first in the screen capture image).   There must be some other error in the task but I need to figure out which expressions I should have confidence in if I am importing a task. We can talk about this on Monday.  Happy weekend.

**Comment by bowring** [comment]
look closely : the ages end in E8  (1/2 billion) - is that in the ballpark?

**Comment by NicoleRayner** [comment]
Perfect.  Got it.
