### ISSUE TITLE
Different Common Pb for unknown and reference material

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#230]
I have a couple of tasks that use different Common Pb for the Reference Material and the unknowns. Is it possible to have both sets inside parameters (eg sComm-64 for the rM and sComm_64u for unknowns)? It is possible that this already exists and I haven't found it yet.

**Comment by bowring** [comment]
This option was not built into Squid directly. We need to discuss with @sbodorkos to understand the use case more fully.  In the short run, you can make custom expressions and use them instead of the defaults within the built-in expressions that handle reference materials and / or unknowns.  To save effort, you could then use the new facility for copying a squid project and replacing the Prawn file so as to preserve your edited task.  Here again, we are on the cusp of making all these features more obvious and robust as we continue to develop Squid.  Thanks for being a contributing user!

**Comment by sbodorkos** [comment]
@AllenKennedy you're a bit ahead of the curve at the moment! In short, all of the functionality implemented under SQUID 2.50's "Group Me" screen remains under construction in Squid3, so it's not available yet, but it will be as soon as I can disentangle it. As you know, there is a fair bit of functionality in there, including (1) the arithmetic for performing a 204-overcount correction on the unknowns (via radio-buttons "Force concordance...", (2) the various options for Stacey-Kramers (or uniform custom) common-Pb corrections for Grouped-sample unknowns, and (3) the guiding parameters (population proportion and threshold probability-of-fit) for applying SQUID 2.50's "Extract coherent age" feature. In general, this is a very poorly known section of the code (not many footprints!), with little change since SQUID-1, and that in turn means that a lot of the VBA code is very hard to read, and the interplay between the 3 aspects defined above is difficult to elucidate (and occasionally non-intuitive, at least to my mind). It turns out that the overcount-related arithmetic is traversed first, so that is where I am currently working. I would imagine the Grouped-sample-specific common Pb is next after that, but I've been wrong plenty of times before...

**Comment by bowring** [comment]
This issue is resolved as of v1.5.0.
