### ISSUE TITLE
BiWeighted Means

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#232]
Is there a generalized form for an equation that produces the mean of a ratio or Cps?

**Comment by bowring** [comment]
Yes: average(["206/254"]) and be sure to select reference material and/or unknown samples  as well as summary calculation in the checkboxes under the expression name.  The right hand top button takes you to some videos that may help.  

You can build this expression using the drag-n-drop functionality: click 'Create Blank' button, drag-n-drop the math function 'average' from the entities list at bottom left into the expression building area, select 'replace mode' at top, drag-n-drop ratio from ratios list on left onto the dummy 'ARG0' argument supplied with 'average', select 'reference material' checkbox (for example) and select 'summary calculation' checkbox, then click 'Save' button and the result will appear in the peek window at the bottom right.  Once you have name the expression, you can use it as '["name-of-expression"]' in other expressions - it appears in the custom expressions list on left. If you name-of-expression is a simple continuous string with no spaces or special characters, you can use it directly without the brackets and quotations.

For total cps, follow above instructions, but drag-n-drop the Squid function (lower left entities list) 'TotalCps' and replace 'ARG0' with '["206"] ' or '["BKG"]' and do not select the summary calculation checkbox.  One further quirk (now becoming an issue - thanks!) is that for the peek to show the values of TotalCps, you need to multiply by 1 : 'TotalCps(["206"])*1'.

Finally, to calculate the mean of the cps, use 'average(TotalCps(["206"]))' as a summary calculation.

HINT: it may be easier for you to enter expressions as text instead of drag-n-drop - just click the 'Edit as Text' button at the right of the edit window (after you enter edit mode).  Currently you will have to use text mode to enter the isotopes such as '206' into the 'TotalCps' expression, as they are not provided in the lis the list to the left.  This might be an issue if a user thinks it is important?

Thank you for your interest in Squid3!

**Comment by bowring** [comment]
I just noticed the term 'BiWeighted' in the name of this issue - please let me know if I have answered your question.  FYI, Tukeys Biweight per Ludwig is supplied by this 'summary calculation' expression: 'sqBiweight(["206/254"],9)'. (9 is tuning)

**Comment by AllenKennedy** [comment]
JIm,
Thanks, I will digest this today.
Allen

**Comment by AllenKennedy** [comment]
Jim,
I tried 'sqBiweight["208/206"],9)' but didn't get the correct biweight sigma... at least the value returned is nothing like the result from Ludwig's Tukey's Biweight. I am probably doing something wrong and not seeing what?

**Comment by bowring** [comment]
Allen - I will need your Squid file and the Excel file where you are calculating Tukey's so I can understand what you are doing with actual numbers.

**Comment by bowring** [comment]
Allen -

I think the issue may be that Squid3 returns 1 sigma abs not 1 % as sigma.

- Jim

**Comment by sbodorkos** [comment]
@AllenKennedy was this resolved to your satisfaction? If not, could you please paste your list of 208/206 input values, and some representation of the sqBiweight values you are getting from Squid3 (even if just a screenshot)? With that info, I will be able to sort out what's going on...

**Comment by bowring** [comment]
@AllenKennedy is not responding so I am closing this issue.
