### ISSUE TITLE
RM data models - ratios vs ages

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#235]
Starting to build new data models in anticipation of the upcoming new release.  Was going to build a Temora model and note that the only Pb/U data that I can input are RATIOS, not ages.  However, the only published values for this RM are the AGE not the ratios.  Obviously I can reverse engineer this, just wondering if the models should be structured so that the published age can be used when that is the cited reference value.  It's a can of worms - whether or not you want people monkeying around with they ratio/errors on their own or if SQUID3 does the calculation.  One  point that argues for inputting age into the model is that is is the same approach used by SQUID2.x and thus has user appeal.....

**Comment by bowring** [comment]
Great point - I have been wondering how to handle this ... actually only physical constants and common pb are going live in the next release, so hold off on building reference material model for now until we solve this.  I am thinking of having a special class of reference material model that has only ages - Squid3 actually only uses the ages, but is able to calculate them (apparent ages) from the given ratios and uncertainties.  Thoughts - @sbodorkos too?

**Comment by sbodorkos** [comment]
@NicoleRayner @bowring Yes, this is a bit vexed. Essentially we are seeking a balance between catering to the needs of (junior) users who wish only to use authoritative reference materials models, and just want to be sure which ones those are, and (senior) users who might have a reference material supported by unpublished data, or maybe just want to use a guesstimated (or nominal) age for specific purposes.

One possibility might be to have a "two-tiered" system, where some models have ratios AND ages, and other models just have ages. In the first category, the ratios and ages would be internally consistent (for a specified decay constant, of course, which is the other issue with age-based models). In terms of rigour, there are good reasons to go right back to the IDTIMS isotopic ratios (and not just to remove the reliance on the decay constant!) and ensure that their weighted means really do correspond to the reference ages everybody uses (I have done this check for TEMORA2, using the IDTIMS isotopic ratio-data tabulated by Black et al. (2004), and I did get a weighted mean 206/238 that I could convert to a date of 416.78 Ma using the Jaffey et al. (1971) decay constant, which is reassuring!). Perhaps models based on published IDTIMS data, and which pass this check, could be labelled "Verified" (or similar), as another potential means of separating "authoritative" reference material models from "speculative"/"convenient" ones, because as the models proliferate, I think this distinction will become important.

**Comment by bowring** [comment]
fixed in pull request #244 - we introduce a switch that provides for 'Reference Dates' only with no underlying data.  This means once we go live with reference material models in the calculations, Squid retrieves dates from the model in either case - calculated or provided.  Thanks to @NicoleRayner for her input.
