### ISSUE TITLE
No concentration standard dataset

### ISSUE THREAD

**Issue by cwmagee** [CIRDLES/Squid#302]
The following dataset does not include a concentration reference material. It should still be reducable for geochronology, as U/Pb and Th/Pb ratios are not concentration dependent, but obviously any calculations for concentration are not going to work.

[100158_GA6149NK_10120916.52.zip](https://github.com/CIRDLES/Squid/files/3011653/100158_GA6149NK_10120916.52.zip)

**Comment by bowring** [comment]
Thank you for the data set - it exposed a bug in Squid3's processing of spot names by providing a non-standardized set of names, which the latest version v1.1.5 of Squid3 can now handle. In the case of this file, I chose to use the leading 4 characters of the spot names as the delimiter, since the file contains both "." and "-" delimiters. Since you don't provide a reference material model, I created one for Temora at age 417 Ma and assigned it to the spots named "TEM-" and did not specify a concentration reference material.  Since you don't provide a task, I used the default 10-peak task supplied with Squid3 and reduced and graphed the data.  All  expressions depending on concentrations evaluated to zero.  @cwmagee - please use Squid3 v1.1.5 and repeat these steps (or similar) and revisit this issue.  Thanks for your input!

**Comment by cwmagee** [comment]
I used Simon's Temora ref mat model:
[TEMORA2 dates only v.1.0.zip](https://github.com/CIRDLES/Squid/files/3015941/TEMORA2.dates.only.v.1.0.zip)

**Comment by bowring** [comment]
Are you satisfied with the resolution of this issue?

**Comment by cwmagee** [comment]
I lost compressed air and my water chiller on Friday, so I will be working in physical space for a while. Gimme a few days.

**Comment by cwmagee** [comment]
I think it is working now, although it took me a while to realize that the reason nothing was plotting was that a reference material parameter model was not selected. A flag somewhere downstream of the data tab might be handy there.
cheers,
Chuck
