### ISSUE TITLE
Custom reports not being generated in v1.1.8

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#317]
I can create sanity checks, and the whole folder structure is there for squid2.x reports, just no files.  There is no folder structure for squid3 for ETREDUX reports.  In issue #182 I had this same problem and it was related to not having defined the samples in the Sample naming menu, but that isn't the case here.  
Here's my file:
[954_1_2019_May_01_15.02.squid.zip](https://github.com/CIRDLES/Squid/files/3142591/954_1_2019_May_01_15.02.squid.zip)

**Comment by bowring** [comment]
I ran sanity reports then ran ET_Redux report and got this - see screenshot
<img width="701" alt="reports" src="https://user-images.githubusercontent.com/1092963/57150290-e4f30100-6d9b-11e9-99f2-d09176cdc81a.png">

**Comment by NicoleRayner** [comment]
It works for me now too but I am stumped.  I experimented with a lot of different things before making the issue - different orders of things, clearing out the reports folder, restarted squid etc.  What I hadn't done before making the issue and sending to you was saved the latest squid project (after importing a new pd file).  It was only in doing that that I realized the workflow issue when bringing in a new file.  So maybe there are some "order of operations" type gremlins in there.  I will keep an eye on it.

**Comment by NicoleRayner** [comment]
This is still a problem for me.  I open a squid file, check the visualizations (ref mat wtd mean and unknowns concordia) to make sure things look normal then I go to Reports--> Custom-->Unknowns--> by sample for ETREDUX and Topsoil.  It creates the folder structure but there is nothing in there. I quit squid and tried again, this time doing the sanity check first.  I get the sanity check files but not the others.

One thing I noticed when I created this issue the first time, and then was unable to re-create it, is that when it DID properly create the report files, it opened it automatically in Excel.  Now (as before) I get nothing...is there some system setting that it could be choking on? It wants to open the file but is unable?  I've this same process with Excel 2016 closed and open (at the time of making the reports) to no avail.

**Comment by bowring** [comment]
This must be related to opening Excel automagically on WIndows ... I will make all reports just saved and leave it to the user to open them if needed.

**Comment by sbodorkos** [comment]
@NicoleRayner I asked Jim @bowring to disable the auto-open functionality because I am running two version of Excel and the auto-open behaviour was causing me grief, so that one is on me. I asked for a conventional "Save As..." window in its place (because I always need to change the name of the file!), but we have not gone that way yet. 

One issue I had last week (and I was supposed to write it up, haven't done it yet) was that the directory path for saving Reports is keyed to the Project Name (as specified in the Manage Project window), **not** the name of the .squid file, and it took me a long time to work that out. The interim solution will be to tie the Project Name and the .squid file name together (i.e. if you change one, you change the other), until we have a chance to look more closely.
