### ISSUE TITLE
Visualization defaults - make them "sticky"

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#322]
While my personal opinion is that the default settings for concordia diagrams should be 2s error ellipses with _**no**_ centre dots (currently 1s and with centres),  I can appreciate that others mileage may differ (or not?  @sbodorkos? @cwmagee? @ryanickert? - maybe we all agree that this should be the default).

In any case, once the user changes the visualization preferences for one sample within a squid project, it would be great if stayed that way for all samples within that project.

**Comment by ryanickert** [comment]
I agree with the importance of sticky default settings, particularly for visualisations.  Once someone really gets cranking, being able to avoid doing the same sets of clicks'n'drags every time makes the process much more efficient and pleasant (this is an issue in standalone topsoil as well).  Personally I'm a 95% person, but I'd take a default of 2sigma any day over 1sigma.

**Comment by NicoleRayner** [comment]
Now that I think about it, I am a 95% conf person too.  This is actually what Isoplot plots when you select a 2sigma plotting level (regardless of what the label at the top of the diagram says).

**Comment by sbodorkos** [comment]
I think this is another thing that could be incorporated into a classical 'Preferences' structure (albeit at different levels), which we don't have much of, at present. Down the track, we'll need to think about which controls represent "set and forget" style Preferences, and which are important enough that they need to be re-presented to (and confirmed by) the user in each data reduction... and categorising the two probably won't be straightforward.

A 'preferred SigmaLevel' control would be quite high up, because in theory it should dictate the preferred format of your data-tables as well (i.e. ±2sigma uncertainty-columns to match your ±2sigma error ellipses/bars in visualisations), as well as magnitude-matching of key parameters obtained from the primary reference material (i.e. spot-to-spot error and session-to-session error for calibrated daughter-parent ratios). We are already running up against some of these issues in "StandardData" portrayals, where we have implemented the choice of index isotope (for common Pb correction) in the form of a visualisation control. However, the selection has quite far-reaching implications for the numerical values in the ReferenceMaterialReport CSV output by Squid3, and that is not at all obvious from the Visualisation... ReferenceMaterial... WeightedMean screen.

Conversely, the presence or absence of centre-dots would be a relatively low-level Preference relating specifically to Concordia graphics. (I quite like the dot — a frustration with the Ludwig ellipse is that the eye is always drawn to its perimeter, when your actual measured value is unmarked in the centre — but that is purely a personal preference.)

**Comment by NicoleRayner** [comment]
I just noticed this today,  but while the selection of 1sig vs 2sig for a given sample will "stick" if you go from one sample to another, the label will not (if I change to 2sig, view/plot a sample with 1sig then back again to the first (2sig) sample, the label stays as 1sig even though the original plot itself is unchanged (2sig).

**Comment by bowring** [comment]
[handled in v1.5.5](https://github.com/CIRDLES/Squid/releases/tag/v1.5.5)
