### ISSUE TITLE
Getting fancy with a monazite task - crashes when applying task labels?

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#335]
I have attached the corresponding files below but here is the behaviour:

- Start a new squid project with a 12 P monazite task
- Define the RM. Define the samples.  Select the RM model.  All good
- Import Squid2.5 task (this is a task where Pb/U is primary system, Pb/Th determined directly - I can't recall offhand what Perm that is).  Things seem OK.  It is a complicated task though with a bunch of custom equations that use overcounts (in case that explains anything). 
- When I go to apply Task Labels, nothing happens, but SQUID is responsive, I can go to Manage Data then back to Manage Isotopes and it APPEARS that the correct labels have been applied. 
- Now if I go back to Manage Task - no response.
- If I go to Expressions - I get the splash screen.

[IP957 monazite_attempt to clean up task.zip](https://github.com/CIRDLES/Squid/files/3298541/IP957.monazite_attempt.to.clean.up.task.zip)
[957_1_2019_Jun_17_11.15.zip](https://github.com/CIRDLES/Squid/files/3298545/957_1_2019_Jun_17_11.15.zip)
[SquidTask_MnzGSC = 12pk Y GSC 8153 std (fixed slope)-OVC.TP.zip](https://github.com/CIRDLES/Squid/files/3298564/SquidTask_MnzGSC.12pk.Y.GSC.8153.std.fixed.slope.-OVC.TP.zip)

**Comment by bowring** [comment]
I am on it!

**Comment by sbodorkos** [comment]
@bowring This is Perm2, but I promise I won't look at the files, as there are other things I should be doing!

@NicoleRayner do you employ column-swapping (either in this Task, or more generally?). I have never raised it with Jim (too scared!), so Squid3 doesn't support it, although it has since occurred to me that GA has SQUID 2.50 monazite Tasks which use it. It's probably not a big deal, because I don't think it would be necessary to revisit the VBA code, provided I'm capable of explaining to Jim how it actually "works"...

**Comment by bowring** [comment]
The source of the problem is in poor handling of non-existent function names such as in this case "stdev".  Ludwig does not have this function in the list Les provided me.  If we want to add it, then we need to decide whether we want SAMPLE standard deviation (divide by n-1) or POPULATION standard deviation (divide by n) or both.

@sbodorkos and @NicoleRayner please respond to above.

As a result of this investigation, 
1) I have added function "sum(arg)",  where arg is a per-spot expression that returns the sum of the values of that expression.  The user can construct their own stdev using  "sum" and "count".

2) Added a trap for missing function names.  However, at this time, since we relaxed the standards for naming so that both expressions and functions can have simple string names, Squid3 can't tell what is going on, but now produces an empty result for expressions of the form "XXX(a,b,...,c)" where XXX is not recognized.

**Comment by NicoleRayner** [comment]
stdev was a function we used in a custom equation - we wrote it assuming that excel functions work in squid, which was apparently correct but we didn't really give it much thought.  In this particular instance it is the stdev of the SAMPLE.  I can't think off hand of other such functions that I would want to use but of course the problem is these things are hard to predict/recall.    I would be inclined to say that if we are going to add one stdev, we should just add both but that might just be the thin edge of the wedge.

Instead is there a way for empty results (such as this with an undefined function) to also end up in the Unhealthy expressions window. Then at least it would be obvious where there is a problem, even if the nature of the problem was not 100% obvious.  

As someone here has pointed out, very few people write tasks (and probably 30% of those who do are reading this right now) so I don't think we need any major heroics to save us from ourselves.  Just a little hint of where to find the flaw.

**Comment by sbodorkos** [comment]
Seems like there are two issues here. 

1. Being able to recognise "native Excel" functions invoked by SQUID 2.50, so Squid3 at least knows what is happening when those Tasks are loaded/imported. The trick here will be to document the Excel 2002-2003-specific syntax, because changes in newer versions of Excel are not relevant to SQUID 2.50.
2. Deciding how far we want to go in terms of remapping the Excel 2002-2003 syntax to the "native Java" function I presume Squid3 would invoke in order to perform the same operations. As @NicoleRayner says, this need not be comprehensive; it might be simplest to just map the arguments common to both the Excel and Java functions, and prompt the user for anything additional needed.

In terms of "native Excel" functions that might be invoked by SQUID 2.50 Tasks, I have come up with the following (alphabetical) list, some of which we have already dealt with (the links are to help handle Excel syntax). Italics denote potentially lower-priority, but that is purely my own subjective judgement. No need to deal with all of these at once - the main idea is to give a flavour of "native Excel" functions that might be invoked in amongst the specialised Isoplot and SQUID functions (e.g. Biweight, RobReg, WtdAv etc, as well as AgePb76, Pb76, etc) described previously and separately. I suppose this list also serves to illustrate the kind of"general" functionality Squid3 users might want, when constructing custom expressions in new Squid3 Tasks.

ABS [https://support.office.com/en-us/article/abs-function-3420200f-5628-4e8c-99da-c99d7c87713c](url)
AND [https://support.office.com/en-gb/article/and-function-5f19b2e8-e1df-4408-897a-ce285a19e9d9](url)
AVERAGE [https://support.office.com/en-us/article/average-function-047bac88-d466-426c-a32b-8f33eb960cf6](url)
COUNT [https://support.office.com/en-us/article/count-function-a59cd7fc-b623-4d93-87a4-d23bf411294c](url)
_COUNTIF_ [https://support.office.com/en-us/article/countif-function-e0de10c6-f885-4e71-abb4-1f464816df34](url)
EXP [https://support.office.com/en-us/article/exp-function-c578f034-2c45-4c37-bc8c-329660a63abe](url)
IF [https://support.office.com/en-gb/article/if-function-69aed7c9-4e8a-4755-a9bc-aa8bbff73be2](url)
LN (i.e. natural logarithm) [https://support.office.com/en-us/article/ln-function-81fe1ed7-dac9-4acd-ba1d-07a142c6118f](url)
LOG (i.e. logarithm to specified base; defaults to 10) [https://support.office.com/en-us/article/log-function-4e82f196-1ca9-4747-8fb0-6c4a3abb3280](url)
MAX [https://support.office.com/en-us/article/max-function-e0012414-9ac8-4b34-9a47-73e662c08098](url)
MEDIAN [https://support.office.com/en-us/article/median-function-d0916313-4753-414c-8537-ce85bdd967d2](url)
MIN [https://support.office.com/en-us/article/min-function-61635d12-920f-4ce2-a70f-96f202dcc152](url)
NOT [https://support.office.com/en-gb/article/not-function-9cfc6011-a054-40c7-a140-cd4ba2d87d77](url)
OR [https://support.office.com/en-gb/article/or-function-7d17ad14-8700-4281-b308-00b131e22af0](url)
ROUND [https://support.office.com/en-us/article/round-function-c018c5d8-40fb-4053-90b1-b3e7f61a213c](url)
SQRT [https://support.office.com/en-us/article/sqrt-function-654975c2-05c4-4831-9a24-2c65e4040fdf](url)
STDEV (i.e. standard deviation of the sample) [https://support.microsoft.com/en-au/help/826349/description-of-the-stdev-function-in-excel-2003-and-in-later-versions](url)
_STDEVP_ (i.e. standard deviation of the population) [https://support.microsoft.com/en-gb/help/828103/differences-between-the-excel-statistical-functions-stdevpa-and-stdevp](url)
SUM [https://support.office.com/en-us/article/sum-function-043e1c7d-7726-4e80-8f32-07b23e057f89](url)
TINV [https://support.microsoft.com/en-au/help/828340/excel-statistical-functions-tinv](url)

It would be nice to have the "equivalent" Java functions available in the Expression Manager, so that similar functionality could be implemented in the building of new Tasks (albeit probably with different syntax). For existing Tasks, mapping Excel functions to Java functions would be useful, but mapping arguments/syntax less so (unless it 's trivial); people will work out the translation for themselves.

**Comment by bowring** [comment]
Great list - we already have 11 of them.  The others are straightforward.

**Comment by bowring** [comment]
version v1.5.0 handles most of the issues here including the completion of the function list proposed by @sbodorkos .  Further refinements can be requested with new focussed issues.
