### ISSUE TITLE
Manage Expressions  gives Alert "Manage isotopes to initialise expressions"

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#343]
Data loads fine, Task loads, but the above Alert appears and there are lots of Unhealthy Expressions. However, the visualisation plots are correct for both RM and Unks, and, most of the CSV file is fine, although U concentrations are 0. Parent Element Concentration constant is X in the Manage Current Task window.
I would guess there is a fix for this that I am unaware of, as I am way behind everyone else with SQUID3 debugging.
[SQ3AX102task.zip](https://github.com/CIRDLES/Squid/files/3335268/SQ3AX102task.zip)
[xenoJG1AX102csv.zip](https://github.com/CIRDLES/Squid/files/3335270/xenoJG1AX102csv.zip)

I have attempted to zip the files in question again

**Comment by bowring** [comment]
thes unzip fine ... will examine problems

**Comment by bowring** [comment]
The issue here is the use of different quotation marks in the excel task from those previously encountered.  This task uses ' “ ' and ' ” ' .  
Squid3 is being updated to replace these with the standard ' " '.

@AllenKennedy - keep up the good work of contributing your experiences so we can find abd squash bugs and improve the feature set.

**Comment by bowring** [comment]
more details here: https://www.cl.cam.ac.uk/~mgk25/ucs/quotes.html
