### ISSUE TITLE
Incorrect identification of the reference peak in a task

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#354]
I loaded a rutile and then a titanite task. The first has a Ti3O3 reference peak , and the second a CaTi2O4 reference peak. Both reference peaks were identified as Th peaks by SQ3.

**Comment by sbodorkos** [comment]
Hi @AllenKennedy , the issue here is the relatively crude logic Squid3 uses to try and 'guess' for each mass-station whether it is a U-bearing peak, a Th-bearing peak, or neither (None). Squid3 essentially bases its guess on the user-specified (in the SHRIMP Control software) Label of each mass-station, remembering that Squid3 does not demand nuclide-by-nuclide specification of each peak in the run-table during Task construction, the way SQUID 2.50 did.

In terms of an immediate fix, note that Squid3's guesses are user-editable. In the Manage Isotopes window, if you right-click on the "Thorium" part of the CaTi2O4/Ti3O3 row, it should open a small drop-down list containing "Uranium", "Thorium", and "None". Select "None", and you've corrected Squid3's guess. (As we refine the user-interface, I'd like the existence of that dropdown to be advertised by a little downwards-pointing triangle; we'll get to that in due course). 

I am not exactly sure how Jim @bowring has implemented the guess-logic, but I too have noticed spurious Thorium peaks in the past, in some of your REE-bearing Tasks. Based on your issues, I suspect the Label search might be solely on upper-case "T". If this is the case, the logic could be tidied by refining the search string to **case-sensitive** occurrences of "Th". Assuming that U-bearing peaks are being detected based on the occurrence of **upper-case** "U" in the Label, we probably don't need any changes.

@bowring , an additional measure that might help mitigate misdiagnosis of "None" peaks as U- or Th-bearing would be to designate a minimum Trim Mass, below which all peaks are "guessed" to be "None". I don't think we would want to be too prescriptive about how good the magnet field calibrations are from lab to lab (because unlike SQUID 2.50, Squid3 does not mandate a maximum permitted divergence between the nominal mass and the true mass of any given peak), but I think we could say that any mass-station with a **trim-mass less than (say) 228 amu** should default to "None" rather than "Uranium" or "Thorium", regardless of what the mass-station label says. In theory, sub-228 peaks should be too "light" to contain any U or Th (with the exception of double-charged ions, which I think we can safely leave to users to configure manually, as per my instructions to Allen above).

**Comment by bowring** [comment]
1) it would be nice to have the raw data file and squid file for examination
2) currently, the logic is:
      if the elementName contains any of "238, 254, 270, u, U" , it is U-bearing, else
      if the elementName contains any of "232, 248, 264, t, T" , it is T-bearing, else 
      none
My conclusion is that there is an anomaly in the data, which I need to investigate once I have the files.

**Comment by sbodorkos** [comment]
And again, with the security-tag this time :(.
________________________________

**Comment by cwmagee** [comment]
If the logic calls anything with "t" or "T" thorium, then that is the problem. Minerals with titanium in them (Ti) usually contain a bit of uranium, and thus are sometimes used for dating. They will generally have a Ti-bearing matrix peak in the run table, as Allen describes. So the logic is too permissive. After all, people who are also interested in trace elements might slip Eu, Lu, Tb, or Tm into their run tables (either as elements or as oxides). And people trying to quantify surface contamination will occasionally measure Au, to see how effectively the raster sputters away the gold coat.

**Comment by bowring** [comment]
Fixed in release v1.3.0 beta - but note we have no way to test it as an example file has not been submitted.  Please report if it works properly.

**Comment by sbodorkos** [comment]
@bowring, following up yesterday's Skype, here is a file that should allow you to test your fix. The screenshot below contains the answers that Squid3 *should* give:

![image](https://user-images.githubusercontent.com/17473203/70209444-5eb0fa00-1784-11ea-8e56-066f783fb3b2.png)

and a ZIP of the corresponding Prawn XML files for testing is here:

[MattCoble_MC78-UO2vUF_17060115.23.zip](https://github.com/CIRDLES/Squid/files/3925408/MattCoble_MC78-UO2vUF_17060115.23.zip)

**Comment by bowring** [comment]
Test successful, screen shot attached
![SquidIssue354TestSuccess](https://user-images.githubusercontent.com/1092963/71004642-27114e80-20b0-11ea-8c6a-ba615d149996.png)
