### ISSUE TITLE
Future enhancement... save button for RM XML files

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#361]
Would it be possible to have an autosave button for Reference Material Models, so that the RM model is written as an XML file into a designated folder? This would save work for anyone with a large number of RM.

**Comment by sbodorkos** [comment]
Hi Allen

Yes, we are still working out how to handle the various categories of Model. Jim @bowring sees the XML versions of the Models primarily as a sharing/portability measure; once you get hold of someone else's Model and use it in your Squid3, it gets ingested, and will always be available to you, even if the XML version of the Model is subsequently lost.

The benefit of this approach is that all your Squid3 Projects that depend on any given Model do not break if the XML Model file gets lost. The flipside at present is that it's hard to manage large volumes of Model data: if you have 56 RMs, 73 Tasks etc., it's hard to browse them in order to choose the one you want. I am hoping we will be able to institute some 'list-views' to ease that process.

I also hope we will be able to streamline the generation of 'editable' RM Models by simplifying the LabData interface. At the moment, we are still guessing how people are going to use RM Models; we intend to build golden 'non-editable' ones for widely used RMs that have published IDTIMS data, and we envisage those will be popular with ordinary users.

Power users will no doubt want to define their own 'editable' models as needed, for experimental purposes, and for those, the main value will be in ensuring the preservation of full metadata associated with a specific data-reduction (similar what SQUID 2.50 tries to do, with the text in the top-left of the StandardData sheet, and the reference-value boxes mostly arrayed down the right-hand side of the StandardData sheet).
________________________________

**Comment by bowring** [comment]
@sbodorkos and @AllenKennedy - Let's revisit this with some real models and develop some use cases that we can implement.

**Comment by bowring** [comment]
this should be handled by v1.5.10 with single and bulk export of parameter models, although no auto-save feature exists.
