### ISSUE TITLE
SK calc error

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#365]
First of all, so great to have a new version of squid to play around with.  I have an even greater appreciation for the "Group Me" labyrinth that needed to be untangled.  

There seems to be a problem with the calculation of the SK ratios however.  What is being reported as the 7/6 ratio is actually the 7/4.  It should be SingleStagePbR(AGE, 1)/SingleStagePbR(Age, 0).  Likewise what is being reported as "8/6" ratio is actually 8/4.

![set common pb comp SK](https://user-images.githubusercontent.com/40035242/67334006-83605380-f4ef-11e9-95f7-000863abf56c.JPG)

**Comment by sbodorkos** [comment]
Yes, and I suspect the error also occurs in the related arithmetic (i.e. using Nicole's example, the calculations are using common 207/206 = **15.6006** when the TRUE value of common 207/206 is actually (207/204)/(206/204) = 15.6006/18.1726 **~ 0.86**). Analogously, TRUE common 208/206 values are near 2, not ~38. 

This arithmetical error will also be the source of many of the large negative apparent ages, and the NaNs as well. I am optimistic that most of the rest of the arithmetic is fine (because the 4cor_206Pb238U data, which is the only value unaffected by the above, looks fine). Having said that, it is clear that I need to audit the arithmetic as it applies to the unknowns, starting with the SampleData ("all unknowns") output that predates v1.3.0.

**Comment by bowring** [comment]
Addressed in release v1.3.1 beta
