### ISSUE TITLE
Common Pb/204 overcount interfaces - proposal for new layouts

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#381]
@sbodorkos @allenkennedy @cwmagee  this issue goes out to you three (and any others in the SHRIMP community who are lurking on this Github)
I am really excited about all these new developments on SQUID3!  I feel like if our IT folks confiscated our old Excel 2003 data reduction computer tomorrow we wouldn't be screwed!  Better than that, we'd be FINE.  Thanks so much to @sbodorkos and @ryanbarrett1515  for all their hard work. 
With the primary functionality worked out, I have given some thought to the interface, and this particular github issue addresses how to simplify our interactions related to common Pb.  What I am proposing is that we group together the "204 count correction" actions with the "assign common Pb" actions. I have mocked up what this could look like - see the image below but have also attached it as a pdf.  

![WM layout proposal](https://user-images.githubusercontent.com/40035242/71373405-11ef6080-2585-11ea-991f-2aadec0a9874.jpg)

I think that this layout sensibly and efficiently puts all the info related to common Pb corrections (which includes the 204 OVC issue) in one place.  The only thing that is "lost" is seeing all the the ages (6/38, 7/6, 204 corr, 207 corr, 208 corr etc) for all the **individual analyses** (you can still see the effect on the summary age of changing your common Pb comp or OVC choice).  I feel like this more concise view is worth it however, not having to use 2 menus to accomplish one thing.  If you want to see side by side comparison of the different individual ages/corrections you can do that in the report settings.  This just my opinion however, Let me know what you think....(no rush,  I know it is Christmas/summer holiday time in Oz. Just putting this out there for future consideration).

[CommPb layout proposal.pdf](https://github.com/CIRDLES/Squid/files/3995710/CommPb.layout.proposal.pdf)

**Comment by sbodorkos** [comment]
Hi @NicoleRayner - it looks and sounds good to me. I think we only segmented and sequenced the screens that way because that is how the 'Group Me' code is laid out in SQ2.50, but I think yours is a sensible idea. 

But I still haven't been able to look at any of these screens 'live' - I haven't had access to a fully functioning Sq3 since v1.3.x about a month ago, and I know I have a lot of catching up to do.

Where do you think we should display the biweight Overcount204from20X values and their 95% confidence intervals, as calculated from the set of RM values? I have discussed this with @bowring a couple of times, and every time I end up suggesting something different... do you think they should appear on the RM Wtd Av screen, your remodelled screen depicted here, or in both places?

**Comment by NicoleRayner** [comment]
I think the biweight Overcount204from20X values and errors should be in this remodelled screen, I will have to think about where/how.  Maybe the dropdown item which are currently listed as "ovc from 207 and ovc from 208" could include these values?  Or insert an additional column that once a selection is made gets populated with the appropriate RM value/error?  We don't use OVC very often, so my workflow on this topic might not jive well with yours. Other suggestions welcome.

I think that we might want to come up with way of outputting a number of summary calculations for RM's so that might be an additional "Report" type.  The suggestions above aren't meant to take the place of that functionality.

**Comment by bowring** [comment]
version 1.5.0 will demo a solution for further discussion.
