### ISSUE TITLE
238U/235U values in model

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#479]
Since it is not super obvious to many that the 238/235 value in SQUID3 lives in the RM Parameter model, I would suggest that this value is also output in the "Select Isotopic RM Model" window  (see red arrow).  Also include the caveat that if the value is n/a then 137.818 is assumed (same message as currently pops up when you are selecting common Pb, as I recall....)
![238U235U ratio of RM](https://user-images.githubusercontent.com/40035242/88426800-c83b5280-cdbf-11ea-9d55-d1ec30614138.JPG)

Relatedly, we use value 137.88.  I don't ever remember changing that, so I presume this is the default value that comes with SQUID2.x (@sbodorkos?).  If this is indeed the case, that this is the value most squider's currently use, I would suggest that this becomes the default.

**Comment by bowring** [comment]
@sbodorkos - Thoughts on changing default back to 137.88 ?

**Comment by NicoleRayner** [comment]
OK @ryanickert I'll send all the SQUID2.x users who are freaking out because the numbers coming out of SQUID3 aren't the same your way..... ;)

**Comment by ryanickert** [comment]
Just tell them that it could be worse - they could be making Ar-Ar analyses! :)

**Comment by cwmagee** [comment]
A few points:
Is this the value used to calculate ages for unknowns, or the value  used in the reference zircon? Most TIMS people have stopped using the 1970's value (137.88), so if the reference TIMS data uses the modern (137.818) value but you want to push out data consistent with old (pre 2012) datasets using 137.88, then you will need to use both values in the correct place and neither in the wrong place.

It may not matter if we are using old analyses for reference values, but as soon as people start using modern CA-TIMS numbers, they will need to know which value was used for their reference 7/6 ages.

Ideally everybody should move to the new value, but institutions with large legacy datasets may not have the funding to migrate everything yet, and mixing dates calculated with different rations is asking for trouble.

Since the old value is hardwired in Squid 2, as long as people are running comparative tests between squid 2 and squid 3 we will need to use that for comparative purposes.

**Comment by bowring** [comment]
Thanks for the comments.  Squid3 is designed to use parameter models (following on ET_Redux's approach), wherein the model for a reference material specifies the 238/235 ratio.  Note that these models can describe either a TIMS-generated set of ratios with calculated apparent ages or simply a set of ages. Thus, users can have have two differently-named models for the same reference material as a solution to the conundrum posed by @cwmagee - one from the past and one from TIMS, to use as needed. The 238/235 value in these models is used both in the processing of reference materials and samples.  Currently, if the user fails to specify a value for 238/235 in their model, the default Squid3 provides is 137.818 as announced in a pop-up window.  

As a solution to the issue raised by @NicoleRayner , I propose that when the user selects the reference material model in the "Data / Manage Spots and Reference Materials" screen, that Squid3 alerts the user if there is a missing (zero) value for 238/235 and provides a choice of 137.88 or 137.818 for the current project.  

Question: Per @cwmagee 's first point - should Squid3 support a second value of 238/235 for processing unknowns?

Thoughts?

**Comment by sbodorkos** [comment]
@bowring my feeling on that last question is NO, we never want more than one value for present-day 238/235 in any one Project, for exactly the same reason as we never want more than one value for any given decay constant in any one Project. This is why I have always believed that 238/235 should have been modelled as a Physical Constant with respect to SHRIMP U-Pb data processing workflow. 

The "proof" of this lies in the way we are now distributing 238/235 = 137.818 to all of our newly-generated RM models: 137.818 is not the value measured in each and every one of our them (as our model-structure currently implies); rather, 137.818 is a reasonable representative value for terrestrial zircons, based on the experimental data presented by Hiess et al. (2012). Which means it's a thing that looks an awful lot like a physical constant, in terms of our workflow (which differs from the RM-less workflow of IDTIMS data-processing). 

Obviously there remains a choice of 238/235 value for users, but a similar choice theoretically exists for the 235U decay constant (Jaffey et al. 1971 vs Schoene et al. 2006), so this shouldn't preclude 238/235 being modelled as a physical constant.

In terms of SQUID 2.50 vs Squid3 comparisons, the reason we need to retain 238/235 = 137.88 as an option is because SQUID 2.50 and Isoplot3 do not mesh perfectly... Isoplot3's Numeric Preferences supply you a window in which you can specify your own 238/235 value, but unfortunately that value is only used in the Isoplot code. SQUID 2.50 has its own value of "NatUrat": it's 137.88, and not user-editable. So specifying a value of 137.818 in the Isoplot3 Preferences, in conjunction with SQUID 2.50, is likely to yield something unrepeatable with respect to replication in Squid3. 

I would love to fix this in the VBA code (i.e. so that the user-specified 238/235 value was used for all invocations of NatUrat everywhere), but I don't think I am competent to do it properly. Moving between SQUID and Isoplot was complicated even for Ken, to the point where he started duplicating Isoplot functionality in SQUID modules just to avoid it.

**Comment by ryanickert** [comment]
Just to speak specifically to Chuck's points about RMs:  The choice of 238/235 for ID-TIMS analyses will have a tiny effect for 206/238 ages.  For U235-spiked (or 233U-235U spiked) analyses, it will affect the amount of natural 235U that is subtracted from the spike prior to either U-mass fractionation or calculation of the amount of 238U via isotope dilution.  This effect is essentially impossible to deconvolve quantitatively for published data, though it's certainly possible to estimate the effect for typical analytical conditions.  It's almost certainly too small to worry about in the context of a SIMS RM, not least because most RMs are still not as well characterized as they could be.

It will have a larger effect for reference 207/206 ages (if used), but in that case, it's straightforward and simple to recalculate from the published radiogenic 207Pb/206Pb, which does not require knowledge of U isotope composition or concentration.

(FYI I"m planning on some TEM2 ID-TIMS measurements over here to get us up and running, so if you have anything peculiar or specific you want measured let me know)

**Comment by cwmagee** [comment]
Hi Ryan,
If you are interested in running the aliquots with differing d18O described in Schmitt et al. 2019 (link: https://ecat.ga.gov.au/geonetwork/srv/eng/catalog.search#/metadata/127430 ), let me know and I'll see if Axel can send you some of those grains.
cheers,
Chuck
