### ISSUE TITLE
Calibration slope mismatch warning

### ISSUE THREAD

**Issue by cwmagee** [CIRDLES/Squid#491]
Is it possible for SQUID 3 to give us a warning if:
1: for a non-floating calibration slope, if the fitted calibration slope for the reference zircon is NOT withing undertainty of the value used in the calibration equation.
2: For any unknowns grouped int oa single age, if the calibration slope of that group is not withing incertainty of either:
2a. The slope value in the calibration equation
2b. The slope of the reference zircon, OR
2. The slope of any other unknow groupings of the session
?

**Comment by NicoleRayner** [comment]
Basically there is no facility for warnings that accompany expressions.  And to maintain ultimate flexibility, I don't think we want to "bake" them in as inevitably you will want to do the "?" in your list above.
It might be possible to write an expression for point #1 (although getting a "warning" is a different matter)
Making comparisons with individual unknowns can't be done automatically because each squid project has different unknowns.  You can certainly check all that stuff individually on a case by case basis and even build custom expressions for that purpose but ultimately you would have to check the output of those "manually". 

Maybe one could build a separate "warning" utility that allows you to select any two expressions to compare but that is a brand new can of worms.

**Comment by bowring** [comment]
Closing this discussion until someone wants to re-ignite it.
