### ISSUE TITLE
Incongruous reference material parameters

### ISSUE THREAD

**Issue by cwmagee** [CIRDLES/Squid#537]
Hi all, I was wondering how the reference material models deal with obsolete numbers. For example, most published reference material model references from before 2010 (the Hiess et al. paper) will have assumed the wrong 238U/235U ratio, which means that the 207Pb/206Pb ages and ratios will not match up. Is squid3 smart enough to know what to do with this problem, or should we not used reference ages from pre 2010 papers, and only input reference ratios instead?

**Comment by NicoleRayner** [comment]
Hi Chuck,  I'm not sure I understand what you want/need when you say "deal" with obsolete numbers.  SQUID3 uses/does whatever you tell it. In the ref mat model you can specify the 238/235.  The ones that are built in has 137.88 because that is the one baked into SQUID2.5 and we wanted to ensure reproducibility of the numbers.  You can always make a new model with your preferred value.  And once you use that model in  your .squid file is it recorded in perpetuity as the one that was used to reduce that data (and if you export your data, it is included in there too).

**Comment by cwmagee** [comment]
Thanks Nicole. I hadn't thought of the reproducibility issues. Don't tell Simon.
