### ISSUE TITLE
xml file will not load

### ISSUE THREAD

**Issue by dmole01** [CIRDLES/Squid#558]
Squid3 Version: 1.6.7
Java Version: 1.8.0_281
OS: Mac OS X 10.14.6

Issue details:
Xml files from the attached sessions will not load up in sq3. I get an error message (attached). The data were collected at Curtin, I believe on SHRIMP B.

[DM_YIL-9_16100814.47 2.zip](https://github.com/CIRDLES/Squid/files/5845031/DM_YIL-9_16100814.47.2.zip)
[DM_YIL-8_16100109.57.zip](https://github.com/CIRDLES/Squid/files/5845042/DM_YIL-8_16100109.57.zip)
![Screen Shot 2021-01-20 at 14 58 12](https://user-images.githubusercontent.com/77752401/105229448-f52fae80-5b31-11eb-8c4d-d7b675f844e6.png)

**Comment by sbodorkos** [comment]
Thanks David @dmole01 , we'll get Jim @bowring to have a look at it, and if it's a parsing issue, hopefully get it fixed for the next release.

**Comment by bowring** [comment]
David @dmole01 and Simon @sbodorkos - I have examined the data files and determined:

1) the XML files are not compatible with the schema we are using - they seem like a first pass from early days;  with considerable effort, a new schema and translator could be developed to parse these - I seek community input as to whether there are enough of these to warrant the effort.  The files also have much fewer metadata and data than the current XML files.

2) The associated OP files are good and allowed me to find a bug in OP-processing.  The next version of Squid3 - v1.6.8 will contain a fix for the bug and allow David to re-open the supplied Squid file for DM_YIL-8_16100109.57 in good working order!

Cheers

**Comment by dmole01** [comment]
Thanks for looking into this @bowring - much appreciated. These data were collected in 2016. I can't be certain, but as many people use those SHRIMP instruments at Curtin, including GSWA, there may be lots of xml files of this kind out there. Have GSWA reported any issues?

**Comment by bowring** [comment]
dmole01 - this is the first instance of seeing these files so we will have to wait and see.

**Comment by dmole01** [comment]
No worries @bowring. Let me know if I can help out further.

**Comment by NicoleRayner** [comment]
Hopefully Allen Kennedy can chime in,  I can't seem to @ him anymore....

**Comment by bowring** [comment]
dmole01 - I have created a new schema for these files and can read them in!  Note however, that if other flavors of these exist, we may need to tweak the schema to get it to work.  Also, Squid3 can write these older files out in the new format and read them back in as proof!  Could Squid2.5 even read these?  See next release for these features.

**Comment by dmole01** [comment]
Thanks @bowring - great news. I suspect that most people have reduced their 2016 data in squid 2.5, so perhaps these old formats wont be a problem unless someone wants to do whole-sale re-processing of old datasets. I am not sure if sq2.5 could read these - I have always used the pd file for data reduction, not the xml.

**Comment by sbodorkos** [comment]
@bowring I know this one is closed, but I think it's likely to be the tip of the iceberg. We need to bear in mind that the vast majority of the SHRIMP community has **never** used the Prawn XML file until Squid3 forced them to; most users processed the text PD file instead, because it was smaller and faster through SQUID 2.50, and easier to manipulate manually via text-editor. 

Ludwig made little use of the power of the XML file in SQUID 2.50; so users processing PD files lost very little functionality. Columns containing spot-specific QT1Y, QT1Z, and Primary Beam (nA) values are pretty much all the 'extras' that Ludwig delivered from XML.

It is possible/probable that the SHRIMP-A Prawn XML file supplied by @dmole01 is an extreme case, owing to the specialised SHRIMP control software which is probably linked to the manufacturing vintage (~2000?) of the multi-collector fitted to that instrument. But only time will tell.

**Comment by bowring** [comment]
Bring 'em on!

**Comment by cwmagee** [comment]
The SHRIMP-A software shouldn't be too old. ASI updated SHRIMP A software when we serviced the multicollector in early 2015. However, the software version we replaced was ancient, so any SHRIMP-A files generated before February 2015 could be in a very old format.

**Comment by dmole01** [comment]
I went back and checked my diary from 2016, and both these session were collected on SHRIMP-B at Curtin.

**Comment by RubyMarsden** [comment]
Hi I know this issue is closed, but I have a similar problem with my xml files generated on the SHRIMP B at Curtin, they are from later than 2018 (as that is when I started my pd). Using SHRIMP 3 v1.7.4 I get the same error.
![image](https://user-images.githubusercontent.com/55971366/112432816-5c5d1f80-8d7c-11eb-9e28-114752104f95.png)
I am trying to test something for @sbodorkos and currently cannot!
@bowring would you like me to send you my xml file? I can make a new issue as well if you prefer - but this seemed like the right thread to be following!
Thanks!

**Comment by NicoleRayner** [comment]
Hi @RubyMarsden - @bowring is definitely going to need your xml file, so if you can zip/add it here that would be good.   I think Jim can re-open a closed issue, so I think it makes sense to keep it all together in this thread.  

On the off chance that a gremlin snuck in somewhere down the track, have you tried opening this file with v1.6.8, which was the first version where this issue was resolved? Doubtful that this will work, but if it does would be good to know.

**Comment by bowring** [comment]
yes please send file as this message implies we need to update the xml schema used - just zip and drop it here

**Comment by RubyMarsden** [comment]
[xml_files.zip](https://github.com/CIRDLES/Squid/files/6212167/xml_files.zip)

Here's my oldest and newest SHRIMP work from 2018-19.
I couldn't find v1.6.8 it seemed to go from 1.6.7 - 1.7.0 and so I tried 1.7.0 but it still didn't work.
Thanks

**Comment by bowring** [comment]
Apparently the software naming scheme for the shrimp is more complicated than assumed so far.  This problem is fixed in the next release of Squid3.  In the short-term you can replace the software version line in your xml file with this line (although I don't recommend making a practice of it):
``` xml
<software_version>SHRIMP SW v3 SHR 2</software_version>
```
