### ISSUE TITLE
Details of Java 1.8 problem (and solution?) experienced by USGS user prior to 18 January?

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#559]
@NicoleRayner @bowring  I am sure I remember you talking, before the Europe Zoom meeting, about a USGS user of Squid3 who had contacted Nicole (I think) late last week with an issue related to Java 1.8. 

I believe this was the issue that led Jim to test and approve the Liberica Java 1.8.

Could I please pester either or both of you to document both that problem **and** its solution as far as you possibly can? It occurred to me that the problem outlined by John Aleinikoff in the Americas Zoom meeting might be exactly the same one you have already solved, and it might be that every USGS user thinks they are hitting it individually. 

I think it would be also good to know the details of how to enact the solution (e.g. if you have got hold the USB version of Liberica, what are the details on how you use that to actually get Squid3 running?

**Comment by NicoleRayner** [comment]
I can add a bit of insight.  This USGS user did not have Java 1.8 installed and was told by his IT department that he was not permitted to have it on his computer.  @bowring suggested Liberica as an alternative.  This can be downloaded from:
https://bell-sw.com/pages/downloads/#/java-8-lts
 
Be sure to download the "full jre" or "full jdk" instead of the standard - download the zip file and unzip.  It can be used without any installer or admin : jre8u275-full.jre/bin/java -jar Squid3-1.6.7.jar (or whatever the most recent version of Squid3 is).

More specific instructions on how to get it running on USB might still be helpful.

**Comment by bowring** [comment]
@NicoleRayner has described the nuts and bolts pretty well.  The key concept with the Liberica zip file is that you can unzip it anywhere you like including onto a thumb drive.  You can then explore its directory structure to see where the java executable file is in the bin (short for binary) folder.  For Windows, you will see both "java.exe" and "java.bat" and for Unix (Linux, Mac) you will see "java".  To use java requires opening a terminal window and being a little familiar with typing commands there.  There are many primers on how to use the command line such as [here](https://www.cyberciti.biz/howto/shell-primer-configuring-your-linux-unix-osx-environment/) for linux / mac, and [here](http://people.uncw.edu/pattersone/121/labs/L1_MSDOS_Primer.pdf) for Windows.

The java executable needs to remain in the bin folder since it is dependent on other files there.  In the terminal you can navigate to the the bin folder using the "CD" for "change directory" in Windows and Unix and then execute the java file by typing in windows ".\java" or in Unix "./java".  Note the different "slashes" used per operating system.  To execute Squid3's current ".jar" file, you can copy it into the bin folder as an *experiment* and the type .\java or ./java followed by "-jar" followed by, for example, Squid3-1.6.7.jar:
Windows: .\java -jar Squid3-1.6.7.jar
Unix: ./java -jar Squid3-1.6.7.jar
This will confirm that all works as intended.

It is preferable not to copy Squid into the bin folder, but rather provide the path to it.  Likewise, you could CD to the Squid jar file folder, and provide the path to the java executable as @NicoleRayner does in the above example.

For more advanced users,  use the installers to add this java to your computer.  To associate ".jar" files with this java, you will have to change the JAVA_HOME environment variable to point to this java.

Good Luck and let us know how this goes!
