### ISSUE TITLE
2010 xml won't open

### ISSUE THREAD

**Issue by cwmagee** [CIRDLES/Squid#577]
The following xml file, from a SHRIMP run in 2010, will not open in v1.7.1. The file has been
-Copied off the SHRIMP computer data hard drive
-renamed
-copied to my current computer using a stick drive.

Project: New SQUID3 Project: From single prawn xml file leave the splash screen up, but nothing further appears. All save options remain grayed out. 
However, trying to reload asks if I want to save the existing Squid3 project changes. Saying YES generates a file which I will attach.,

Opening that project works.
Note that this xml file appears to have only one analysis. Perhaps that is the problem?
[source and save file.zip](https://github.com/CIRDLES/Squid/files/5908346/source.and.save.file.zip)

**Comment by bowring** [comment]
@cwmagee - Thanks!  The problem was the single spot in the data file, which is now handled more robustly in the next release v1.7.2 (forthcoming).  I had made the apparently erroneous assumption that there would be more than one sample.  This assumption when combined with an empirical observation that the use of a sample-naming convention in terms of sample name delimiters in the example files we have was sometimes missing from the first sample name (generally a reference material) led me to chose to use the second sample name as a starting point in detecting the delimiter.  Obviously this does not work with a singleton sample, which is now processed correctly. Another bug was found in the process relative to removing the single spot, which is now also handled robustly.  It is nice that our issues are at this level of minutiae as it may mean that the overall performance of Squid3 is found to be healthy. Cheers!

**Comment by sbodorkos** [comment]
It is possible that Squid3 should reject any Prawn XML with runs = 1, especially if it gives rise to other issues in the data-processing chain down the track. I don't think we lose much by refusing to process such files, and I am pretty sure SQUID 2.50 does not process single-spot files. Just a thought, if further complications arise in Squid3 in this scenario.

**Comment by bowring** [comment]
At this point Squid3 is handling single runs. This incident provided a solution for the user who removes all their runs from a multi-run project as well.  I am for leaving this alone now until / unless someone else comes up with another use case that fails.

**Comment by cwmagee** [comment]
Apologies if this is a stupid workflow question, but for bug reports like these do you want the original reporter to confirm that it is fixed before the issue is closed, or does that happen with your QA/QC before the update goes live?

**Comment by bowring** [comment]
Great question!  Our approach has been for the "assignee" to close the issue after handling it.  If there remains a problem, then the issue can be re-opened by the author of the issue or a new issue can be made.
