### ISSUE TITLE
 Interpretations/unknowns/wtd means...Concentrations and  calculated values not shown...  

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#600]
When I selected Interpretations/Unknowns/Weighted Means/Calc Weighted Means From/Concetrations/Uunk the 204 corrected 206/238 age was still displayed.

<img width="1248" alt="Calc Wtd mean Uunk Screen Shot 2021-03-17 at 3 04 54 pm" src="https://user-images.githubusercontent.com/33318855/111428993-496e9d80-8733-11eb-967b-aca168aa9cc6.png">

**Comment by NicoleRayner** [comment]
Do you have an error associated with Uunk?  Maybe thats the problem.  We can't really help diagnose things unless you zip and attach your file.

**Comment by AllenKennedy** [comment]
Nicole,
Uunk and Thunk were okay when I looked at them under Expressions. Is this zip sufficient? I zipped it with Keka. 

Thanks
Allen


[MAX Xeno.squid .zip](https://github.com/CIRDLES/Squid/files/6162243/MAX.Xeno.squid.zip)

**Comment by NicoleRayner** [comment]
That zipped file worked fine with me.  The problem is that your Uunk has no error associated with it so it can't calculate the weighted mean in that window.  As an aside I'm unsure why you even have that as a custom expression as it duplicates a pre-existing built in expression....

![image](https://user-images.githubusercontent.com/40035242/111630844-27275f00-87c9-11eb-82de-3158234c3274.png)

If you want to calculate a BIWEIGHT (which does not need an associated error) you can do that in custom expressions.  The function is found under "Squid functions - Common" and you replace the Arg0 with either U Concen or your custom Uunk.   The "9" is a tuning factor, the usual default one in isoplot. Note that you will need to make a separate "summary expression" for each sample (otherwise you get the biweight for all samples combined).
![image](https://user-images.githubusercontent.com/40035242/111632342-bed97d00-87ca-11eb-959e-944adf1c9d8f.png)

**Comment by AllenKennedy** [comment]
Hi Nicole,
Thanks. I hadn't paid any attention to whether there were uncertainties associated with Uunk, which was something I dragged in from a SQ2.5 task.
