### ISSUE TITLE
Can't read any of the new captions in the Audit screen

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#614]
When I visit the Audit Data screen, this is what I see (and nothing I do inside Squid3 can change it):

![image](https://user-images.githubusercontent.com/17473203/116344643-f0ae1c80-a829-11eb-9721-dfae64c0026e.png)

So I am not sure what the orange button, the check boxes or the radio buttons actually do.

Possibly this screen needs re-designing, but I think it might be useful to think about what sorts of Audit data are useful to view 'session-at-once', and which are more useful only 'spot-at-once'. For the former, we are talking about most of our traditional "raw" audit-data types; for the latter, I think we are talking about most of the "new" audit-data types, relating to total counts across the various mass-peaks. (I am not sure of the value of portraying those data in session-view...?).

The one dataset that would be potentially useful to view in both modes is SBM.

I think branching into a Session Audit screen and a Spot Audit screen might ease some of our issues with regard to both real estate on the screen, and also potentially memory and performance.

**Comment by NicoleRayner** [comment]
Hmmm, I don't have the issue with truncated buttons.  Similar things have happened to others due to display/screen magnification settings.  As for the "new" audit types - I definitely want to see these in session view and in fact this was the purpose of this audit, primarily to find your analyses with bad SBM/counts and exclude them.  I just want to scroll on by and see where the dropouts are.  I'm not sure how one would use/what the purpose would be of a spot-at-once function, but would be interested to hear your ideas on this.  I am not sure if branching will resolve these memory issues since I had such a problem even when the SBM audit was elsewhere.

**Comment by bowring** [comment]
@sbodorkos  says this is resolved thanks to @NicoleRayner .
