### ISSUE TITLE
Audit screen plots broken

### ISSUE THREAD

**Issue by TPestaj** [CIRDLES/Squid#622]
Squid3 Version: 1.7.8
Java Version: 1.8.0_281
OS: Windows 10 10.0

Issue details:  I have broken the audit screen plot area such that the inspection window can still be moved, but the underlying plots do not re-draw.  One incarnation looks something like this:
![image](https://user-images.githubusercontent.com/43234276/117478806-9b5ec300-af2d-11eb-9742-4aff1239183d.png)

which turns into this when I fiddle with the 'Display normalized time axis' button:
![image](https://user-images.githubusercontent.com/43234276/117479198-07412b80-af2e-11eb-9383-755d00bac22b.png)

I have not figured out a reliable way to induce this, but for me it happens while manipulating the sliders associated with the plots.  I will update if I can figure out a specific sequence that leads me here, but I think just clicking/sliding about in this screen will eventually lead to this kind of trouble.

I've tested this only with the included demo data so I imagine it's not a weird data file causing the trouble.

**Comment by bowring** [comment]
Noted - a quick fix for now is to reload the page from the menu.

**Comment by TPestaj** [comment]
Release 1.7.9 makes the plots more robust on my setup such that I have not been able to break them (yet :)).  But I think I have discovered how to cause trouble.

Toggling the 'Display normalized time axis' off/on changes how large an increment the inspection window moves when using the horizontal slider above the plots; i.e. initially slider moves the window in steps of one analysis, but toggle time axis and slider now moves steps of two, etc.  Eventually, the step size becomes large and not-so-friendly to use.

The workaround of reloading the page from the menu still works.

**Comment by AllenKennedy** [comment]
I have the same audit issue with the attached SQ3 file for 1.7.9. Toggling didn't solve the issue. Reloading didn't work, Resetting didn't work. Is this issue related to the earlier issue with Data names? In the SQ3 file I have attached the RM is labelled B. Under Data, Manage-Sample Names, anything longer than B cannot be selected. I cannot select BR, BR2, BR231, BR231. When I click on the selection box for each of these the next box down is highlighted, but not selected. I also noted that in the Concordia plot for the unknowns there is a shift away from the concordia. Looks like the issues in 618 and 624.
[A19 JHZ.squid.zip](https://github.com/CIRDLES/Squid/files/6463596/A19.JHZ.squid.zip)

**Comment by bowring** [comment]
There are a couple subjects here:
1) The audit raw data window works fine for me ... can you send screenshot of issue?

2) In order to change the naming pattern for the reference material you need to clear the reference material choice from the selection boxes for both types and then return to the naming screen to select your naming scheme.  The workflow was designed to proceed with this selection first, then the specification of the reference materials.  The reason you can't change the check boxes after you have populated the reference materials is to protect them.

3) I have discovered that the problem with this file is related to the naming of the samples - Squid3 is weak in understanding sample names that do not follow the expected pattern involving a delimiter - in this case, "."  So, in this case, simply un-choosing the RMs, renaming "BR231" to "BR231.", then reselecting the RMs fixes the issue and prevents miscalculations under the hood.   However, the "A" and "T" samples are missing until they are renamed "A." and "T.".  This is a bug in the sense that Squid3 makes the assumption based on available training data during development that the naming scheme would be consistent.  If the community feels Squid3 should be more robust then we need to define the use cases.  One simple fix is to alert the user to the fact that the sample naming scheme is not being followed and propose the fixes mentioned - the addition of the delimiter, for example.

@AllenKennedy - thank you for your diligent critiques!

**Comment by AllenKennedy** [comment]
Here is a screen shot of the Audit window
I think alerting the user of inconsistent naming and that they must use a delimiter is sufficient

<img width="1249" alt="Screen Shot 2021-05-12 at 12 54 12 pm" src="https://user-images.githubusercontent.com/33318855/118062731-304c3b00-b3ca-11eb-80e5-c4539bac4af5.png">

**Comment by AllenKennedy** [comment]
My comment about the shift on the concordia may be incorrect, and just a difference attributable to using different RM.

**Comment by NicoleRayner** [comment]
Issue 622 seems to be conflating two things.  This issue as original posted by Tom relates to the audit window going a bit wonky sometimes – you get blank spots and can’t “access” some parts of the data. I will try and see if I can get it to screw up and tape it as the example. This happens on our files that very consistent file naming (- delimiter always). 

I’m not 100% clear why the delimiter stuff was raised in this issue – it came up initially in issue #624 (the  Concordia not plotting).  I think Allen may have conflated that and the Concordia shift problem he identified because he _thought_ he was having that problem again here but it was just that he changed something in his RM.

I think we should move this file naming/delimiter thing to a new issue.

**Comment by bowring** [comment]
@AllenKennedy - The naming / delimiter thing is fixed and published in the next release - v1.7.10 with a more robust parsing of names and a warning popping up when names don't comport with chosen delimiter.

@AllenKennedy - your screen shot looks normal - the slider above the graphs moves the zoom window left and right so you can see more detail.

@TPestaj  -The issue of using the slider in non-normalized time mode is problematic - one sultion may be to turn off the zoom in when time is not normalized.  Suggestions welcome.

**Comment by bowring** [comment]
After release of v1.7.10, let's make new issues for each of these items as appropriate.
