### ISSUE TITLE
Trouble Accessing SQUID 3

### ISSUE THREAD

**Issue by Bethmoore64** [CIRDLES/Squid#653]
![Java](https://user-images.githubusercontent.com/90377489/132641687-346c4aa2-b98b-4826-8c9e-32d18b0c7abf.png)
Hello,
I am trying to run SQUID 3 on my Lenovo laptop. Its running windows 10 and Java 1.8 has been installed, however when I attempt to open the JAR file, it asks me to open with an app. Regardless of what I open it with, I am unable to access the software. The photo attached is what happens when I try to open it with the JAVA on my laptop. Is there any suggestions on something I should try to trouble shoot this?
Thank you!
Beth

**Comment by NicoleRayner** [comment]
Hi Beth,  
I'm no Java wizard but the one thing that strikes me as unusual is that you don't have the .jar extension on the file in the image above.  When I download it, it shows as Squid3-1.8.4.jar, and I double click it and all is well.  Maybe try adding the .jar?  If that doesn't do it, you might search the Issues for "Java" and see what comes up.  Be sure to search both open and closed issues - in other words make sure there are not filters in the search box at the top of  the issues page.

**Comment by bowring** [comment]
This seems to be an issue with Java on your machine.  The ".jar" not showing is a function of how you set up your file browser - to show extensions or not.

The nice thing about Java is you can have several versions at once on the same machine since Java lives in any folder you put it.

For example, if you download the Liberica full JDK for Windows here: https://download.bell-sw.com/java/8u302+8/bellsoft-jdk8u302+8-windows-amd64-full.zip

and then unzip it anywhere you want, say a folder called "C:\MYJAVA" you can run Squid3 in the following way:

1) using a terminal window (cmd), navigate to the folder where you have the Squid3 jar file

2) type  C:\MYJAVA\jdk8u302-full\bin\java.exe -jar Squid3-1.8.4.jar 

Please report back on progress.

**Comment by bowring** [comment]
@Bethmoore64 - any progress / news?  We are here to help!

**Comment by bowring** [comment]
seems there is no interest here anymore ...
