### ISSUE TITLE
default "Save As" file location

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#670]
Any chance of tweaking Squid3 so that the default file Save As location is the same path/folder as the source xml? 
Currently the default file save as location is the last place you saved a file....

Now that I am using squid3 in production, this would be very helpful to avoid errors.

**Comment by bowring** [comment]
We need a use case study, since this could get dicey if someone moves a squid file and does not want it saved at the original xml location - including the case where that location is non-existent.

So, how about: when you load a data file for a new project, Squid3 automatically prompts you to save the .squid file in the same folder?

**Comment by bowring** [comment]
done in v1.9.3 (soon)
