### ISSUE TITLE
Comparison of Custom Ln(208/232) and NU-switched Ln(Pb/Th)

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#696]
Can we provide an explanation of the difference for a user
[Screen Shot 2022-03-29 at 11.48.37 am.zip](https://github.com/CIRDLES/Squid/files/8367879/Screen.Shot.2022-03-29.at.11.48.37.am.zip)
[Screen Shot 2022-03-29 at 11.48.50 am.zip](https://github.com/CIRDLES/Squid/files/8367880/Screen.Shot.2022-03-29.at.11.48.50.am.zip)
[Screen Shot 2022-03-29 at 11.49.07 am.zip](https://github.com/CIRDLES/Squid/files/8367881/Screen.Shot.2022-03-29.at.11.49.07.am.zip)
?

**Comment by AllenKennedy** [comment]
I had expected both axes to be identical and the regression to be a 45 degree line?

**Comment by AllenKennedy** [comment]
Here is the .squid file

[XENOF36A18210323 16pk Dy, Ho, Yb.squid.zip](https://github.com/CIRDLES/Squid/files/8367974/XENOF36A18210323.16pk.Dy.Ho.Yb.squid.zip)

**Comment by AllenKennedy** [comment]
An odd regression. Is there a strange pt located outside the plot window that is skewing the regression
[Screen Shot 2022-03-29 at 12.34.47 pm.zip](https://github.com/CIRDLES/Squid/files/8368084/Screen.Shot.2022-03-29.at.12.34.47.pm.zip)
?

**Comment by sbodorkos** [comment]
**Screenshot 1:**
![InkedScreen Shot 2022-03-29 at 11 48 37 am_LI](https://user-images.githubusercontent.com/17473203/160604161-f1c3955a-5215-4d88-b027-db01b24e9068.jpg)

**Screenshot 2:**
![InkedScreen Shot 2022-03-29 at 11 48 50 am_LI](https://user-images.githubusercontent.com/17473203/160604617-31df9ff3-3f93-4426-ab79-3ab7ae52db24.jpg)

@AllenKennedy the source of the divergence is analogous to the NU- vs FO-switches in SQUID 2.50. 

The first expression (where "NU-switched" is blank) is simply taking the natural log of the spot 208/232 value (and ignoring the associated %err value). This is the equivalent of the FO-switch in SQUID 2.50, and you could verify this result from Squid3 output by using Excel's LN function with the spot 208/232 value as the argument.

The second expression (with "NU-switched" ticked), is calculating N-1 values of ln(208/232) [where N is the number of scans], with each value time-interpolated between scans. Uncertainties for each interpolated value are calculated numerically by perturbing each of the inputs. A "spot-mean" value (and its uncertainty) is generated either by taking a time-invariant weighted mean of the interpolated values, or by linear regression to burn midtime. This is the equivalent of the NU-switch in SQUID 2.50.

Here is the relevant section of the SQUID 2.50 Manual which compares and contrasts the two calculation methods:

![image](https://user-images.githubusercontent.com/17473203/160604025-28fefb99-b74e-42ee-89b9-e27086a8aa5b.png)

The detail of the arithmetic is given in the SQUID 2.50 User Manual, from the base of page 43 to the base of page 46. All of these steps have been faithfully replicated in Squid3. The PDF is here in case it's handy:

**[squid2_user_manual_2.5.zip](https://github.com/CIRDLES/Squid/files/8371190/squid2_user_manual_2.5.zip)**

Re your second regression, I'm not sure what the issue is there.

**Comment by bowring** [comment]
For second issue, change LnpbU to be NU-switched and then both terms will have uncertainties and the regression will work.  BTW it is best to not use "/" symbol in expression names - Squid will ignore it and will eventually remove it.

see attached image:
![regression](https://user-images.githubusercontent.com/1092963/160613649-5f261d14-7cf4-4c30-8c90-6b91baac2c52.jpg)

**Comment by bowring** [comment]
BTW, you could also alter LnpbU to have a constant 1 percent uncertainty for example:
valuemodel(ln(["206/238"]), 1 , false)

which will also plot correctly

**Comment by AllenKennedy** [comment]
Hi Simon,
Thanks for the explanation. I was aware of the different switches. I don't like identical typeset equations giving different results, as it has the potential to confuse users. Also, I don't think we should ever let users of SQUID3 produce numbers without uncertainties, no matter what was done in SQUID 2.50.

**Comment by sbodorkos** [comment]
Hi Allen, I don't know what we can do about the typesetting of expressions. We mimicked SQUID 2.50 because I had neither the authority nor the expertise to do differently. And one benefit is that we do get to refer to the SQUID 2.50 documentation to explain aspects of the functionality (even if not all of that functionality is desirable).

We can't mandate errors in inputs, so I don't think we can mandate errors in outputs. And there are plenty of areas of the data-processing where uncertainties (both input and output) are unimportant, unquantifiable, or both. Anything involving U (ppm) is probably a good example.

**Comment by AllenKennedy** [comment]
Simon,
Maybe the uncertainties on some parameters are too small to change calculated results and affect outcomes, but that doesn't mean they should not be calculated or given if it is possible. At the simplest level, counting stats (Poisson distribution) gives us an uncertainty for every peak we measure and at least an approximate uncertainty for every ratio. Truly unquantifiable parameters is a very scary concept and they should be identified in some way.
