### ISSUE TITLE
Expression "Total_207Pb206Pb" needs an error as well as a value

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#697]
As discussed previously, we need this column in order to plot Tera-Wasserburg data uncorrected for common Pb... but because it is exactly equivalent to ["207/206"] and hasn't had any arithmetic done on it, it has slid through the expression evaluation as a Value without an error:

![image](https://user-images.githubusercontent.com/17473203/161471142-e68f76fb-453c-48a7-a4a0-1d3d8100c678.png)

I guess Total_207Pb206Pb probably needs a ValueModel? I also wonder whether defining expression Total_207Pb206Pb as type "NU-switched with Uncertainty" is an alternative way of yielding a value and error that is identical to ["207/206"] in all respects.

**Comment by NicoleRayner** [comment]
Why not just actually use ["207/206"]?  That is what I am doing in my custom reports.

**Comment by bowring** [comment]
Total_207Pb206Pb has uncertainty at Total_207Pb206Pb[1]. One fix for peek and reporting is to have Squid3 recognize the underlying ratio and present the full picture.

Another way to do that, as @sbodorkos says is with Total_207Pb206Pb = ValueModel(["207/206"],[±"207/206"],true).

NU-switching will not accomplish this for simple ratios since the math for ratio calculations has already been done through Dodson interpolation, see https://github.com/CIRDLES/ET_Redux/wiki/Development-for-SHRIMP:-Step-3 .

The NU-switch math is done in another routine involving perturbation of an expression's ratios of interest (only available for use in the presence of at least one of these ratios of interest), see:
https://github.com/CIRDLES/ET_Redux/wiki/SHRIMP:-Sub-EqnInterp

**Comment by sbodorkos** [comment]
Yeah... I know the issue _can_ be worked around. But it's not the way Squid3 _should_ work. 

I want people who are looking to assemble the Tera-Wasserburg report-block for uncorrected data to be able to do it as easily/intuitively as possible, which is the same reason Ludwig defined ["207/206"] and Total_207Pb206Pb as separate fields/columns in SQUID 1 and 2 in the first place. The ValueModel seems the obvious way to sort it out.

**Comment by bowring** [comment]
Squid3's original Calamari report engine correctly reports both value and uncertainty for Total_207Pb206Pb in the old "Unknowns - per Squid 2.5" (found in misc reports).  Having the peek and new report engine look up and report the value is easy and is not really a workaround just a bug fix - the lookup is being skipped currently due to bad logic.  In addition, the recalculation using the valueModel is using the existing 207/206 uncertainty anyway and the result is off by one digit about 30% of the time due to the recalculation.

**Comment by bowring** [comment]
Fixed in next release v1.9.12
