### ISSUE TITLE
v1.10.1: What is happening with Common Pb?

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#714]
I have a couple of different questions, which I am binding together here because they might be related: I don't know, because I no longer understand how Squid3 treats common Pb.

My Project still has a Default Common Pb model specified in the Manage Project screen, but the Default Model values don't seem to be used anywhere. Instead, in the Expression Manager, common Pb for my Reference Materials seems to be treated exactly as if they were Unknowns. Don't understand this, definitely not what I want, and there doesn't seem to be any way to alter the behaviour (Built-in expression Com_206Pb204Pb, for example, does not seem to be editable).

I don't mind it working the way it currently does for the Unknowns, but for Ref Materials, I want Com_206Pb204Pb (for example) = DefCom_206Pb204Pb. How do I achieve this, when my Common-Pb Model is no longer being used in the Expression calculations?

Possibly related question: why are Expressions classified as "Reference Material Values" or "Parameters" not available in the Custom Report Builder? If I could select DefCom_206Pb204Pb for insertion as a column in my Ref Material template, that would help (although it wouldn't address the fact that the DefCom value is not currently being used to calculate 4cor_Com206Pb_Pct_RM, for example).

Here is a ZIP of my Project file: **[170111_GA6357_Sq3-1.10.1_Perm1.zip](https://github.com/CIRDLES/Squid/files/9084924/170111_GA6357_Sq3-1.10.1_Perm1.zip)**

**Comment by bowring** [comment]
@sbodorkos - definitely a bug where the common lead calculations for the unknowns also were recalculating the common lead for the reference materials in some cases.  This was not caught by our current test suite since it does not cover the common lead calculations.  The new test suite that you are working on will do so.

**Comment by bowring** [comment]
This bug was introduced as a side-effect of changing the default common-lead scheme.  My apologies.  Next release contains fix and more ...

**Comment by bowring** [comment]
Expressions classified as "Reference Material Values" or "Parameters" are not spot-specific, so they were not included in spot reports.  They are included in the Summary Expressions and Values report - which needs feedback and improvement over its initial (and never updated) implementation.  Now that the bug is fixed, everything works as it did before and you can access the common lead values for reference material spots using the spot metadata fields in reports for reference materials.  New version shortly.
