### ISSUE TITLE
Squid 1.10.2 common Pb preferences don't stick

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#724]
The modification that linked the common Pb model selection for the RM to the default common Pb correction for the unknowns (aka a custom common Pb model for the RM = the same model for unknows, or the SK model for the RM = SK for the unknowns) is no longer working.  See issue #704 for further details. I think this was implemented in v1.10.1 but when the common Pb bug was fixed in v1.10.2 it was lost.

**Comment by bowring** [comment]
That turned out to be problematic.  The current mechanism is that in the Project Manager, if the checkbox "Default for Unknowns" is checked and set as the default using the "Set Default" button to the left, then a new project will default the Unknowns commonPb to using the model chosen;  if unchecked and made the default, then Unknowns default to using SK.  The checkbox has no effect after the project initialization so as to not override any decisions made on the CommonPb setup for Unknowns.  We can discuss?

**Comment by NicoleRayner** [comment]
I didn't notice the checkbox before - my mistake.  What you describe above sounds good - and makes sense.  I'm trying to get a bunch of stuff done before heading out for field work on Sunday so would prefer to hold on any discussion (but not even sure if it is necessary!)

**Comment by bowring** [comment]
@NicoleRayner - this still an issue?

**Comment by NicoleRayner** [comment]
No this is good now.  I didn't clue in about the check box before.
