### ISSUE TITLE
Empty per scan reports

### ISSUE THREAD

**Issue by TPestaj** [CIRDLES/Squid#757]
It seems that per scan and/or per spot reports are often empty, aside from column headers.  This seems to happen most often when one splits a file, but here's a screen shot of the demonstration data file's report output, with no modifications made by me (files of 1 KB size only contain column headers).

![image](https://github.com/CIRDLES/Squid/assets/43234276/b9fecbae-3a51-40b1-919d-ec122c77c653)

 I have not found a reliable workaround, but sometimes saving the .squid file, then immediately creating the reports works, sometimes not.

**Comment by bowring** [comment]
@TPestaj - I cannot replicate your issue using Squid v2.0.3 on the demo file on either mac sonoma or windows 11.  Do you have any other examples?

**Comment by TPestaj** [comment]
Hm.  I simply open the demo project and click 'Generate all reports'.  

Here's my setup:
Squid3 Version: 2.0.3
Java Version: 1.8.0_391
JavaFX Version: 8.0.391-b13
OS: Windows 10 10.0

I've zipped an offending xml data file, its .squid file, plus the report folder that is output from 'Generate all reports'. 
[1052_1_2023_Oct_11_14.30.zip](https://github.com/CIRDLES/Squid/files/13354216/1052_1_2023_Oct_11_14.30.zip)

**Comment by bowring** [comment]
the zipped report folder has normal reports inside it 


![reports](https://github.com/CIRDLES/Squid/assets/1092963/f14f6907-0df5-4765-95f8-175c0003d1b3)

**Comment by bowring** [comment]
all files open:

![reports2](https://github.com/CIRDLES/Squid/assets/1092963/b250f94c-63d4-4c48-859e-af072f143a8b)

**Comment by NicoleRayner** [comment]
I wonder if this is going to be some kind of long path name problem.....I have a vague recollection of this before.  Might explain too why sometime the _PartA _PartB for a split file pushes it over the edge but not always.  We can test that....

**Comment by TPestaj** [comment]
Funny, because my folder (the one I zipped up and sent to you) shows me this:

![image](https://github.com/CIRDLES/Squid/assets/43234276/27ed8ac7-544b-428f-af04-d7e92f9a94d8)

**Comment by bowring** [comment]
Try @NicoleRayner ’s idea and put the squid file as close to top of directory structure as you can (c:).

**Comment by bowring** [comment]
@TPestaj - what happens when you unzip the file in a different location?

**Comment by TPestaj** [comment]
Yes, it looks like it has to do with the length of the file path.  Reports output for the demo file work fine if I put it into a different (shorter path) folder.

Unzipping the reports folder above does not change the empty .csv files, though.  Curious why it worked for you.

I tried to change a Windows registry entry to allow for >256 character path names, but that did not help.

Not sure how best to address this as our data folder structure is kind of fixed (other tools rely on the existing structure to find files, etc.).  @NicoleRayner suggested maybe dropping the last sub-folder and putting the last set of reports reports into the '_PerScan' folder (ie no '.._SPOTAV' or '..._LINREG' subfolders), thereby shortening the path.

**Comment by NicoleRayner** [comment]
I could see a couple of options here. 
1) Include a "PerScan" folder but simplify the folder name to simply "PerScan" - no prefix with the squid file  name.   Then I would also simplify the names of the subfolders in there.  Right now it is like this:
![image](https://github.com/CIRDLES/Squid/assets/40035242/0c5e3f4c-8995-438b-8419-e9b3f185e4d4)
Everytime you make one it adds a date/time code to the start that is quite long but not that meaningful - it is really just a unique identifier.  Just a simple addition of a (1) to the end of a folder name if there is a duplicate folder name (in the example below SBM_LinReg
![image](https://github.com/CIRDLES/Squid/assets/40035242/3fc34ae7-42db-4039-8bd0-80b1588d9754)

2) as Tom mentioned just get rid of the PerScan folder altogether and put the subfolders (aka the SBM/NOSBM + LINREG/SPOTAV) one level up.  This could also be simplified by the suggestion above.

I know that for us these simplified folder/file names would not pose a problem because we already keep the .squid files for a given session in separate folders so it is always clear what we are looking at.  @sbodorkos, @cwmagee, anyone else -  any worries?

**Comment by bowring** [comment]
@NicoleRayner - if you run generate all reports more than once, those dates allow for unique reports, in case you were fooling with a parameter, etc.

**Comment by bowring** [comment]
I am going to take the first step and remove the "perScan" subfolder in the next version.  Let me know how it goes.
