### ISSUE TITLE
Provide access to Ludwig's non-radiogenic lead ratio calculator.

### ISSUE THREAD

**Issue by bowring** [CIRDLES/Squid#81]
@sbodorkos noted that Ludwig provides a function to calculate the ratios from a date - we need to determine where it is, implement it in LudwigLibrary, and make it available to the user in a future preferences menu.

**Comment by sbodorkos** [comment]
@bowring Yes, there is a LudwigLibrary-style function, which we will need soon for @AllenKennedy issue #230 . Note that the function (or subroutine, I am not sure which, as I am not running the correct versions of the software at present) lies within the **Isoplot** VBA code (**not** SQUID 2.50), and is called "SingleStagePbR". Inputs are Age (in Ma!!) as Double, and a "WhichRatio" index as Integer, where 0 = 206/204, 1 = 207/204, and 2 = 208/204. Output is a single numeric value of the specified ratio, as Double, calculated assuming single-stage Pb-isotope evolution using the parameters of Stacey and Kramers (1975). 

I think Ludwig designed the code this way so it could easily be invoked as a single-cell function in an Excel spreadsheet, but I think it would probably be a bit smarter to re-implement with a single input (i.e. Age), and a 3-element vector output, being the 206/204, 207/204, and 208/204 corresponding to that Age.

You're welcome to try tracking down and implementing the relevant code on your own if you like, but if it's not completely straightforward, don't waste time on it - just kick it back to me and I will describe it in the wiki.

**Comment by bowring** [comment]
@sbodorkos -

Isoplot3/Pub.bas/SingleStagePbR:
```vba
Public Function SingleStagePbR(Age, WhichRatio%)
Attribute SingleStagePbR.VB_Description = "Stacey-Kramers single-stage 206/204, 207/204, or 208/204 (Which=0,1,2) from specified age"
Attribute SingleStagePbR.VB_ProcData.VB_Invoke_Func = " \n14"
' Pb-isotope ratio from age, assuming single-stage growth.
If IsNumeric(Age) And IsNumeric(WhichRatio) Then
  CalcPbgrowthParams True
  SingleStagePbR = PbR(Age, WhichRatio)
Else
  SingleStagePbR = Menus("ValueErr")
End If
End Function
```

boils down to the following function from Isoplot3/UPb.bas:

```vba
Function PbR(ByVal Age, ByVal WhichRatio%)
Attribute PbR.VB_ProcData.VB_Invoke_Func = " \n14"
Dim Eterm#, wr%  ' Pb-isotope ratio from age, assuming single-stage growth
wr = WhichRatio
Eterm = PbLambda(wr) * Age
If Abs(Eterm) > MAXEXP Then BadExp
PbR = PbR0(wr) + MuIsh(wr) * (PbExp(wr) - Exp(Eterm))
End Function
```
Here Ludwig relies on looking up values:
PbLambda(wr) - returns the lambda for the specified index, presumably 0 = 206, 1 = 207, 2 = 208
Question: what do these other arrays contain with their mysterious names? (I have confirmed that these do not appear as functions in the VBA code base):
PbR0
MuIsh
PbExp

Cheers!

**Comment by sbodorkos** [comment]
@bowring the arithmetic is in the modules; "CalcPbgrowthParams" is actually a subroutine that does a lot of the work. But the arithmetic is so trivial, I will just write it here.

The [Stacey-Kramers model](http://dx.doi.org/10.1016/0012-821X(75)90088-6) approximates Pb-isotope evolution of the bulk Earth since 3700 Ma. The idea is that if you can guesstimate the crystallisation age of a mineral, you can approximate the isotopic composition of the non-radiogenic "initial Pb" incorporated into its lattice at the time of crystallisation. Of course, the abundance of that non-radiogenic component can be inferred by the abundance on non-radiogenic 204Pb.

The terrestrial Pb evolution model parameters used by Isoplot correspond to the **middle row of Table 8 (top of p. 216)**. The model has six relevant parameters, specified below as Parameter = Variable name = double-precision value:

1. 206Pb/204Pb = SK_Alpha0 = 11.152
2. 207Pb/204Pb = SK_Beta0 = 12.998
3. 208Pb/204Pb = SK_Gamma0 = 31.23
4. 238U/204Pb = SK_Mu = 9.74
5. 232Th/238U = SK_KappaMu = 3.78
6. Start age (Ma) = SK_StartAge = 3700.0

Ludwig does the calculations according to the index WhichRatio, where the target ratios are indexed as follows (note that the associated parent nuclides are 238U, 235U, 232Th, in that order):

206Pb/204Pb = 0 
207Pb/204Pb = 1
208Pb/204Pb = 2

He then constructs a few 3-element (**and zero-addressed!!**) vectors for the calculations. Firstly, decay constants (units Ma^-1)

    PbLambda = [Lambda238Ma,  Lambda235Ma,  Lambda232Ma]

Then present-day ratios of parent nuclides according to the model ParRat = [238U/238U, 238U/235U, 238U/232Th], so where Uratio = present-day 238U/235U = 137.88:

    ParRat = [1,  Uratio,  1 / SK_KappaMu] 

Then starting Pb-isotope ratios (i.e. at 3700 Ma):

    PbR0 = [SK_Alpha0,  SK_Beta0,  SK_Gamma0]

Then MuIsh, which is the ratio of Mu to the parent nuclide ratio (MuIsh = SK_Mu/ParRat):

    MuIsh = [SK_Mu,  SK_Mu / Uratio,  SK_Mu * SK_KappaMu]

And finally the exponent term PbExp, combining SK_StartAge and the relevant decay constant:

    PbExp = [exp(SK_StartAge * Lambda238Ma),  exp(SK_StartAge * Lambda235Ma), 
       exp(SK_StartAge * Lambda232Ma)]

Once all these data are assembled, it's easy to calculate the corresponding 3-element vector SingleStagePbR. The sole input is a double-precision TargetAge (in Ma!!; first calculate an Eterm, and then the corresponding SingleStagePbR:

    For i = 0 to 2
      Eterm[i] = TargetAge * PbLambda[i]
      SingleStagePbR[i] = PbR0[i] + MuIsh[i] * ( PbExp[i] - exp( Eterm[i] ) )
    Next i

Output is a 3-element vector of model [206Pb/204Pb, 207Pb/204Pb, 208Pb/204Pb] corresponding to TargetAge, as per Stacey and Kramers (1975). I believe code yet to be documented will utilise the LudwigLibrary function SingleStagePbR iteratively.

**Comment by bowring** [comment]
These issues are handled as of release v1.5.0.
